repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.1
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format

- repo: local
  hooks:
  -   id: tests
      name: run tests
      entry: uv run pytest -v
      language: system
      types: [python]
      stages: [commit]